on:
  release:
    types: [released]

jobs:
  version_bump:
    name: Update project version
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: 🛑 Validate tag name
        run: |
          if [[ ! $GITHUB_REF =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "The release tag name format is incorrect. It must have the following format: \"1.2.3\""
            exit 1
          fi

      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: 🌏 Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: 🏷️ Extract tag name and clean version
        id: extract_version
        run: |
          tag_name="${GITHUB_REF##*/}"
          clean_version=$(echo "$tag_name" | tr -d '.')
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          echo "clean_version=$clean_version" >> $GITHUB_ENV

      - name: ⬆️ Bump version in variables.gradle
        run: |
          sed -i "s/versionCodeVersion = [0-9]\+/versionCodeVersion = ${{ env.clean_version }}/g" android/variables.gradle
          sed -i "s/versionNameVersion = '.*'/versionNameVersion = '${{ env.tag_name }}'/g" android/variables.gradle

      - name: ⬆️ Bump version of package.json
        uses: ramonpaolo/bump-version@v2.3.1
        with:
          tag: ${{ github.ref_name }}
          commit: false

      - name: ☁️ Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'release: ${{ env.tag_name }}'
      - name: Force update the tag to the latest commit
        run: |
          git tag -f ${{ env.tag_name }}
          git push origin --force --tags

  look_version:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: echo version
        run: cat package.json
