name: rollback

on: workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set latest release as pre-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const latest_release = await github.rest.repos.getLatestRelease({
              owner: owner,
              repo: repo
            });
            const currentDateTime = new Date().toLocaleString('es-ES', { timeZone: 'Europe/Madrid' });
            await github.rest.repos.updateRelease({owner: owner, repo: repo,release_id: latest_release.data.id, prerelease: true, body: `# ATTENTION: THIS RELEASE WAS ROLLED BACK\nDate: ${currentDateTime}\n` + latest_release.data.body});
