name: rollback

on: workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set latest release as pre-release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const releases = await github.repos.listReleases({ owner, repo });
            const latestRelease = releases.find(release => !release.draft && !release.prerelease);
            github.repos.updateRelease({ owner, repo, release_id: latestRelease.id, prerelease: true });
